server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"


build:
  version: "3.0"

accounts:
  message: "Welcome to Bank account related local APIs"
  contactDetails:
    name: "Jefferson Celestino - Developer"
    email: "contato@jeffersoncelestino.dev.br"
  onCallSupport:
    - (+55) 031 55555-4444
    - (+55) 031 55555-1234
