spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank account related prod APIs"
  contactDetails:
    name: "Ana Clara - Product Owner"
    email: "contato@anaclara.prod.br"
  onCallSupport:
    - (+55) 061 33333-2222
    - (+55) 061 33322-2211
